apiVersion: v1
kind: Service
metadata:
  name: expensy-backend
spec:
  selector:
    app: expensy-backend
  ports:
    - protocol: TCP
      port: 8706
      targetPort: 8706
  type: LoadBalancer   # was: ClusterIP